### ISSUE TITLE
Smooth Scrolling isn't working

### ISSUE THREAD

**Issue by ben10512** [csbncounter/www#4]
The smooth scrolling (see index button) isn't working on other pages in page href links...

https://css-tricks.com/snippets/jquery/smooth-scrolling/

**Comment by ianmstew** [comment]
Nice use of Github Issues, @ben10512 !

**Comment by ben10512** [comment]
Resolved Smooth Scrolling and added the JS to all pages. Implemented and working. 

Sorry to fill up all your inboxes with extra emails! :)
